#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Title - Integrate python programming with the apache webserver module 

Created on Mon Aug 12 22:56:14 2019
@author: k as root
"""

"""
1. Set up an apache webserver in my LinuxBox
2. edit: etc/apache2/sites-enabled/000-default:
   Add lines:
       AddHandler mod_python .py
           PythonHandler mod_python.publisher
           PythonDebug On
3. Restart apache2: /etc/init.d/apache2 restart"""

## -----< eg. 1 >
def index():
    return "Hello Python on apache"
# Check: start a browser and go to the location "localhost/tests/hello.py/index". 
# It works with "localhost/tests/hello.py" as well.

## ------< eg. 2 >
import time
def index():
        html = """
<html><head>
<title>mod_python.publisher first html page</title>
</head>
<body>
<h1>This page was generated by mod_python.publisher</h1><hr>
The local time of this server is:  %s
<br>The timezone of this server is  :  %s
</body>
</html>
""" % (time.ctime(time.time()), time.timezone/3600)
        return html
</pre>


## ----< eg. 3 >
import time
def index():
        return "index().. nothing here, but you will find some info at get_time .."
def get_time():
        html = """
<html><head>
<title>get_time function</title>
</head>
<body>
<h1>get_time function</h1>
<hr>
The local time of this server is:  %s <br>
The timezone of this server is  :  %s <br>
</body>
</html>""" % (time.ctime(time.time()), time.timezone/3600)
        return html
# Run in browser with url: http://localhost/tests/timesite2.py/get_time


## --------< eg. 4 : forms>
def index():

	return """
<html><head>
<title>Formular</title>
</head>
<body>
<FORM value="form" action="get_info" method="post">
  <P>
	<LABEL for="firstname">First Name: </LABEL>
	<INPUT type="text" name="firstname"><BR>
	<LABEL for="lastname">Last Name: </LABEL>
	<INPUT type="text" name="lastname"><BR>
	<LABEL for="email">email: </LABEL>
	<INPUT type="text" name="email"><BR>
	<INPUT type="radio" name="gender" value="Male">Male<BR>
	<INPUT type="radio" name="gender" value="Female">Female<BR>
	<INPUT type="submit" value="Send"> <INPUT type="reset">
  </P>
</FORM>
</body>
</html>
"""

def get_info(req):
	info = req.form
	first = info['firstname']
	last = info['lastname']
	email = info['email']
	gender = info['gender']
	return """
<html><head>
<title>POST method using mod_python</title>
</head>
<body>
<h1>POST Method using mod_python</h1>
<hr>
Thanks for using our service:<br>
Your first name: %s <br>
Your last name: %s <br>
Your email address: %s <br>
Your gender: %s <br>
</body>
</html>
""" %(first, last.upper(), email, gender.lower())
# Run in browser with url:
#   for form: http://localhost/tests/form.py/index
#   for post: http://localhost/tests/form.py/get_info



# Note: Debug
# https://www.python-course.eu/dynamic_websites.php
